### ISSUE TITLE
Windows cannot find c:\Users\Appdata\...\win\defid.exe

### ISSUE THREAD

**Issue by edgeball** [DeFi-PortfolioManagement/defi-portfolio#1]
When I open the app after install. I'll get this message

Windows cannot find c:\Users\Appdata\...\win\defid.exe

APP Portfolio V1.0

**Comment by DeFi-PortfolioManagement** [comment]
Hello edgeball,

In my opinion, this could have two causes:
1. you did not install the defi app or
2. you are not using windows as operating system?


Am Dienstag, 16. Februar 2021 schrieb edgeball <notifications@github.com>:

**Comment by edgeball** [comment]
well I'm pretty sure I've A windows OS how else would I've been able to install the defi app?
The app starts, but with the error. Even after another install.

**Comment by DeFi-PortfolioManagement** [comment]
Can you please post the complete path?

**Comment by edgeball** [comment]
C:\Users\[username]\AppData\Local\Programs\defi-app\resources\binary\win\defid.exe

I don't even have the "defi-app" folder in my C:\Users\[username]\AppData\Local\Programs
The app starts but the Button "Update Data" is greyed out

**Comment by DeFi-PortfolioManagement** [comment]
The defi-app folder will be generated, during installation of the defi
desktop app. You can download it here: https://defichain.com/downloads/
Our defiPortfolio App uses the defid,exe. With the defid.exe we check if
there is a connection to the blockchain. If the connection exists the
button "update database" will be enabled.


Am Di., 16. Feb. 2021 um 22:57 Uhr schrieb edgeball <
notifications@github.com>:

**Comment by edgeball** [comment]
oh.. right! I did not install the defi desktop app. I thought your app was a standalone

**Comment by NiC0x36** [comment]
@DeFi-PortfolioManagement could you add that in the README.md under 'Getting Started'? I also didn't have the DeFi Desktop App installed yet. Thanks!
