### ISSUE TITLE
Portfolio software crashes PC

### ISSUE THREAD

**Issue by Sumpfi-75** [DeFi-PortfolioManagement/defi-portfolio#53]
Hello,
i installed the software 1.4.1. on my Windows 10 pc and start it. After closing the dfi app i open the portfolio. After push the update button the second window open and i see the programm running. But after one or two minute the screen goes in a black freeze. The pc was down. I tryed it a second time but ist was the same problem.

**Comment by Kolibri1990** [comment]
Hello @Sumpfi-75 ,
can you monitoring your RAM? That should no be. 
The black cmd defid is running and then shut down?
How much GB RAM do you have? Is Update Data starting?

**Comment by Sumpfi-75** [comment]
Hi Kolibri,
update:
i uninstall, wait until now and make a new install. Now it runs.....
I don´t now the mistake. thanks for your attention.

**Comment by Kolibri1990** [comment]
Ok! Hopefully it will not happen again 👍
