### ISSUE TITLE
Sync won't finish, stuck at 99.94%

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFi-PortfolioManagement/defi-portfolio#71]
Sync won't finish, stuck at 99.94% even after eight hours.
Firewall is open
1GB internet speed
DeFi Wallet is closed (was in sync and working fine, V2.4.0)

Windows 10 Pro (20H2 Build 19042.985)
DeFi-Portfolio V1.4.2
![Sync stuck at 99 94%](https://user-images.githubusercontent.com/77509687/120071199-707c1080-c08e-11eb-9656-293d99cfaede.jpg)

**Comment by Darkman-Q-Tester** [comment]
![Sync stuck at 99 94%-2](https://user-images.githubusercontent.com/77509687/120073618-6dd2e880-c099-11eb-8fa8-989d445220a8.jpg)

**Comment by Darkman-Q-Tester** [comment]
![Sync stuck at 99 94%-3](https://user-images.githubusercontent.com/77509687/120084138-3af71780-c0ce-11eb-900d-f23da90fe14b.jpg)

**Comment by Darkman-Q-Tester** [comment]
After restart today, same issue.
Looks like Block 882145 is causing the issue.
![Sync stuck at 99 94%-4](https://user-images.githubusercontent.com/77509687/120094984-a3bcaf00-c123-11eb-90b6-53bf414f9439.jpg)

**Comment by Kolibri1990** [comment]
Thanks for your issue.
The Portfolio App <= 1.4.3 uses the old node please wait for v1.5 which will include the new node with Eunos upgrade
For more information: https://t.me/DeFiChainPortfolio

**Comment by Darkman-Q-Tester** [comment]
Do you know when v1.5 will be available? Eunos is alrady live.

**Comment by Darkman-Q-Tester** [comment]
Thank you Daniel for update and your effort.

**Comment by lawerfx** [comment]
any update on 1.5.0 release? thx

**Comment by Darkman-Q-Tester** [comment]
Works now for me with v 1.5.0

**Comment by AlexanderStruck** [comment]
I can´t sync the blockchain with the portfolio-app. The DeFi Wallet is working fine, but syncing with the portfolio under windows is not working.
Any idea why? Looks a bit similiar to the problem above. Does it have anything to do with the latest update?

![Defi Portfolio Sync2](https://user-images.githubusercontent.com/23423674/155274217-70c974f6-833e-4d61-afcb-401e0735402e.png)

**Comment by AlexanderStruck** [comment]
I can´t sync the blockchain with the portfolio-app. It is working fine with the DeFi wallet. Has it anything to do with the latest DeFiChain-Update? 

![Defi Portfolio Sync2](https://user-images.githubusercontent.com/23423674/155274936-223ff00a-3cc0-4240-8362-abc41a123bd9.png)
