### ISSUE TITLE
Update Data stocks at 42 %

### ISSUE THREAD

**Issue by 3dzug** [DeFi-PortfolioManagement/defi-portfolio#72]
I tried now three times to clear local cache but either the node tooks up all my ram (!70GB) or it stocks at -11 % or 0 % or 42 %. However I do not get the data. As my local blockchain is restored from a snaptshot I also do not know if I get all my reward data.

**Comment by Darkman-Q-Tester** [comment]
Same for me. Not much to sync but takes hours and max CPU load.
Showing 100% but not finishing.
Version 1.5.0
Defi Wallet 2.5.2
![Defi Portfolio 1 5 0_3](https://user-images.githubusercontent.com/77509687/122897895-b43efe80-d34a-11eb-9869-be5af6c8f65f.png)
![Defi Portfolio 1 5 0_2](https://user-images.githubusercontent.com/77509687/122897902-b4d79500-d34a-11eb-9210-c5853c09bce9.png)
Yesterday the same:
![Defi Portfolio 1 5 0](https://user-images.githubusercontent.com/77509687/122897904-b4d79500-d34a-11eb-8f1f-c5771eb213ff.png)

**Comment by Kolibri1990** [comment]
Hello all,

that's n

> I tried now three times to clear local cache but either the node tooks up all my ram (!70GB) or it stocks at -11 % or 0 % or 42 %. However I do not get the data. As my local blockchain is restored from a snaptshot I also do not know if I get all my reward data.

Unfortunately this is not a portfolio error, it looks like the node hangs on the last data. Unfortunately, this is an error of the node and we can't fix it. I am in contact with a developer in the Chain GitHub.

**Comment by Kolibri1990** [comment]
> Same for me. Not much to sync but takes hours and max CPU load.
> Showing 100% but not finishing.
> Version 1.5.0
> Defi Wallet 2.5.2
> ![Defi Portfolio 1 5 0_3](https://user-images.githubusercontent.com/77509687/122897895-b43efe80-d34a-11eb-9869-be5af6c8f65f.png)
> ![Defi Portfolio 1 5 0_2](https://user-images.githubusercontent.com/77509687/122897902-b4d79500-d34a-11eb-9210-c5853c09bce9.png)
> Yesterday the same:
> ![Defi Portfolio 1 5 0](https://user-images.githubusercontent.com/77509687/122897904-b4d79500-d34a-11eb-8f1f-c5771eb213ff.png)

You are un synchronizing step. I don't know why the updating is not starting. Can you check the Log File in the portfolio project folder (settings button)

**Comment by Darkman-Q-Tester** [comment]
Nothing special in the log file
![grafik](https://user-images.githubusercontent.com/77509687/122911917-16523080-d358-11eb-9cc3-5c5b91ddb8ca.png)

**Comment by Kolibri1990** [comment]
> Nothing special in the log file
> 
> ![grafik](https://user-images.githubusercontent.com/77509687/122911917-16523080-d358-11eb-9cc3-5c5b91ddb8ca.png)
> 
> 

How are your settings? Have you choosen Active Wallet?

**Comment by defiuser2** [comment]
Jun 22, 2021 11:22:44 AM portfolio.controllers.MainViewController <init>
INFORMATION: Start DeFi-Portfolio
Jun 22, 2021 11:26:24 AM portfolio.controllers.TransactionController getBlockCount
WARNUNG: Exception occured: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.defichain.io/v1/getblockcount
Jun 22, 2021 11:31:24 AM portfolio.controllers.TransactionController getBlockCount
WARNUNG: Exception occured: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.defichain.io/v1/getblockcount
Jun 22, 2021 11:38:49 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 946158
Jun 22, 2021 11:38:58 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 148458
Jun 22, 2021 11:38:59 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 936157
Jun 22, 2021 11:39:04 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 131136
Jun 22, 2021 11:39:05 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 926156
Jun 22, 2021 11:39:11 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 153618
Jun 22, 2021 11:39:13 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 916155
Jun 22, 2021 11:39:20 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 145681
Jun 22, 2021 11:39:23 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 906154
Jun 22, 2021 11:39:29 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 147259
Jun 22, 2021 11:39:34 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 896153
Jun 22, 2021 11:39:43 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 242871
Jun 22, 2021 11:39:58 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 886152
Jun 22, 2021 11:40:07 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 258164
Jun 22, 2021 11:40:26 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 876151
Jun 22, 2021 11:40:36 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 253421
Jun 22, 2021 11:41:01 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 866150
Jun 22, 2021 11:41:11 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 259847
Jun 22, 2021 11:41:43 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 856149
Jun 22, 2021 11:41:53 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 263200
Jun 22, 2021 11:42:27 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 846148
Jun 22, 2021 11:42:36 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 253486
Jun 22, 2021 11:43:09 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 836147
Jun 22, 2021 11:43:18 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 256821
Jun 22, 2021 11:43:50 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 826146
Jun 22, 2021 11:43:59 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 237442
Jun 22, 2021 11:44:29 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 816145
Jun 22, 2021 11:44:40 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 222341
Jun 22, 2021 11:45:07 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 806144
Jun 22, 2021 11:45:16 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 221372
Jun 22, 2021 11:45:46 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 796143
Jun 22, 2021 11:45:55 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 228113
Jun 22, 2021 11:46:23 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 786142
Jun 22, 2021 11:46:32 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 225518
Jun 22, 2021 11:47:01 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 776141
Jun 22, 2021 11:47:13 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 191370
Jun 22, 2021 11:47:39 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 766140
Jun 22, 2021 11:47:52 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 205582
Jun 22, 2021 11:48:23 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 756139
Jun 22, 2021 11:48:39 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 213477
Jun 22, 2021 11:49:21 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 746138
Jun 22, 2021 11:49:43 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 175714
Jun 22, 2021 11:50:42 AM portfolio.controllers.TransactionController getListAccountHistoryRpc
WARNUNG: 736137
Jun 22, 2021 11:51:16 AM portfolio.controllers.TimerController lambda$run$0
WARNUNG: Exception occured: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.defichain.io/v1/getblockcount
Jun 22, 2021 11:51:23 AM portfolio.controllers.TimerController lambda$run$0
WARNUNG: Exception occured: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.defichain.io/v1/getblockcount
Jun 22, 2021 12:46:15 PM portfolio.controllers.TimerController lambda$run$0
WARNUNG: Exception occured: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.defichain.io/v1/getblockcount

**Comment by Darkman-Q-Tester** [comment]
Ah sorry was on "All Wallets" does this matter?
![grafik](https://user-images.githubusercontent.com/77509687/122916198-ece7d380-d35c-11eb-9a9a-f6bff9ef6cd7.png)

**Comment by Darkman-Q-Tester** [comment]
For me it is now allways working fine. Looks good now.
